// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTGuardChange();

float h;
float t;
float t_guard;
bool t_alarm;

void initProperties(){

  ArduinoCloud.addProperty(h, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(t, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(t_guard, READWRITE, ON_CHANGE, onTGuardChange);
  ArduinoCloud.addProperty(t_alarm, READ, ON_CHANGE, NULL);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
